### ISSUE TITLE
hi, Mr. Melon, could u like to omit '@mln' from all functions?

### ISSUE THREAD

**Issue by changrui** [Water-Melon/Melang#1]
as above.

**Comment by Water-Melon** [comment]
Hi Charles,


Thanks for paying attention to Melang.


You could call me Nik.


@ could not be omitted, it is part of the syntax, but the prefix mln could be concerned to be removed. Actually, there is no naming convention for function names in library, could you give me some advices?


Niklaus

在 2021年1月11日，上午9:38，Charles WANG <notifications@github.com> 写道：

﻿

as above.

**Comment by changrui** [comment]
I see, thanks a lot.

**Comment by Water-Melon** [comment]
The @ in the function call syntax has been removed, thanks for your suggestion.
